### ISSUE TITLE
Web: Accordion style expand of row items to get full detail.

### ISSUE THREAD

**Issue by dekanbro** [raid-guild/caletaXP-web#46]
On user detail page. This can expand to show more detail that has not been truncated. Only one expanded at a time from click or touch. Should be able to use bootstrap

![image](https://user-images.githubusercontent.com/8740799/78183401-139eaf00-7425-11ea-95db-6b745c0709db.png)

**Comment by manolingam** [comment]
added accordion style expansion in this [pull request](https://github.com/raid-guild/caletaXP-web/pull/48)
